### ISSUE TITLE
use memcpy instead of Py_MEMCPY (see <http://bugs.python.org/issue28126>)

### ISSUE THREAD

**Issue by ldo** [tynn/PyAO#1]
it seems `Py_MEMCPY` was only ever a workaround for a performance limitation in Windows. It is now deprecated, so replace it with the more usual `memcpy` call.

[memcpy.patch.txt](https://github.com/tynn/PyAO/files/894917/memcpy.patch.txt)

**Comment by tynn** [comment]
Could you create a pull request for it?

**Comment by ldo** [comment]
No fork, sorry.
